name: Cross Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Deps
        run: >
          sudo apt install libgtk-3-dev libwebkit2gtk-4.0-dev
      - name: Configure CMake
        run: >
          mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
      - name: Build
        run: >
          cd build && cmake --build . --config Release

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: >
          chmod +x ./setup.sh && ./setup.sh && mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
      - name: Build
        run: >
          cd build && cmake --build . --config Release

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: >
          mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
      - name: Build
        run: >
          cd build && cmake --build . --config Release